stages:
  - build
  - test

variables:
  NODE_VERSION: "12"

before_script:
  - npm ci --no-optional

build:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - npm run build --if-present

test:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm test
