stages:
  - build
  - test

variables:
  NODE_VERSION: "12"

build_job:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - npm ci --no-optional
    - npm run build --if-present

test_job:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm test
